//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k22cnt3_tdt_2210900134.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giao_dich
    {
        public int ma_giao_dich { get; set; }
        public Nullable<int> ma_nguoi_dung { get; set; }
        public Nullable<int> ma_the { get; set; }
        public Nullable<int> ma_dich_vu { get; set; }
        public Nullable<decimal> so_tien { get; set; }
    
        public virtual dich_vu dich_vu { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual the_nap the_nap { get; set; }
    }
}
