//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k22cnt3_tdt_2210900134.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class k22cnt3_tdtEntities : DbContext
    {
        public k22cnt3_tdtEntities()
            : base("name=k22cnt3_tdtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dich_vu> dich_vu { get; set; }
        public virtual DbSet<giao_dich> giao_dich { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<the_nap> the_nap { get; set; }
        public virtual DbSet<thong_bao> thong_bao { get; set; }
    }
}
