//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k22cnt3_tdt_2210900134.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_dung()
        {
            this.giao_dich = new HashSet<giao_dich>();
            this.thong_bao = new HashSet<thong_bao>();
        }
    
        public int ma_nguoi_dung { get; set; }
        public string ten_dang_nhap { get; set; }
        public string email { get; set; }
        public string mat_khau { get; set; }
        public Nullable<decimal> so_du { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giao_dich> giao_dich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thong_bao> thong_bao { get; set; }
    }
}
