//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k22cnt3_tdt_2210900134.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thong_bao
    {
        public int ma_thong_bao { get; set; }
        public Nullable<int> ma_nguoi_dung { get; set; }
        public string noi_dung { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
